media_folder: "uploads"
public_folder: "/uploads"
media_library:
  name: uploadcare
  config: {}

backend:
  name: git-gateway
  repo: Eason-Eternity/life
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/9943dc6b-266a-4824-b37c-b97fcf2d9e4d/pkce
  auth_token_endpoint: /sites/9943dc6b-266a-4824-b37c-b97fcf2d9e4d/token
  gateway_url: https://gateway.decapbridge.com

collections:
  - name: "diary"
    label: "日记"
    folder: "content/diary"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "照片", name: "image", widget: "image", required: false}
      - {label: "正文", name: "body", widget: "markdown"}
      - {label: "标签", name: "tags", widget: "list", required: false}

commit_messages:
  create: Create {{collection}} "{{slug}}" - {{author-name}} {{author-login}}
  update: Update {{collection}} "{{slug}}" - {{author-name}} {{author-login}}
  delete: Delete {{collection}} "{{slug}}" - {{author-name}} {{author-login}}
  uploadMedia: Upload {{path}} - {{author-name}} {{author-login}}
  deleteMedia: Delete {{path}} - {{author-name}} {{author-login}}
  openAuthoring: Message {{message}} - {{author-name}} {{author-login}}

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://days.xin
